name: Terraform

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: List files in working directory
      run: ls -R ./terraform  # Adjust if your .tf files are in a different directory

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Create or select workspace
      run: terraform workspace select ${WORKSPACE_NAME} || terraform workspace new ${WORKSPACE_NAME}
      working-directory: ./terraform
      env:
        WORKSPACE_NAME: dev  # Change this to your desired workspace name

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
